### ISSUE TITLE
Native extensions don't build on M2 Mac

### ISSUE THREAD

**Issue by yoonwaiyan** [eliias/isorun#221]
Hi, I'm trying to install isorun in my new rails app but my installation failed with this error message:

```shell
Using isorun 0.1.13 (was 0.1.12) from https://github.com/eliias/isorun.git (at main@8596156)
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/isorun-8596156a30e5/ext/isorun
/Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/bin/ruby extconf.rb
checking for clang... yes
checking for clang++... yes
checking for ar... yes
checking for cargo... yes

current directory: /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/isorun-8596156a30e5/ext/isorun
make DESTDIR\= sitearchdir\=./.gem.20240115-1771-hsbtg2 sitelibdir\=./.gem.20240115-1771-hsbtg2 clean

current directory: /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/isorun-8596156a30e5/ext/isorun
make DESTDIR\= sitearchdir\=./.gem.20240115-1771-hsbtg2 sitelibdir\=./.gem.20240115-1771-hsbtg2
generating target/release/libisorun.dylib (release)
cargo rustc  --manifest-path ./Cargo.toml --target-dir target --lib --profile release -- -C linker=clang -L native=/Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib -L
native=/Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib -L native=/opt/homebrew/opt/gmp/lib -C link-arg=-Wl,-multiply_defined,suppress -C
link-arg=-Wl,-undefined,dynamic_lookup -l pthread
error: failed to parse lock file at: /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/isorun-8596156a30e5/Cargo.lock

Caused by:
  package `deno_core` is specified twice in the lockfile
make: *** [target/release/libisorun.dylib] Error 101

make failed, exit code 2

Gem files will remain installed in /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/isorun-8596156a30e5 for inspection.
Results logged to /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/extensions/arm64-darwin-22/3.2.0/isorun-8596156a30e5/gem_make.out

  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:120:in `run'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:53:in `block in make'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:45:in `each'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:45:in `make'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:188:in `build_extension'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:222:in `block in build_extensions'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:219:in `each'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:219:in `build_extensions'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/installer.rb:839:in `build_extensions'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/source/path/installer.rb:28:in `post_install'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/source/path.rb:244:in `generate_bin'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/source/git.rb:201:in `install'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/installer/parallel_installer.rb:156:in `do_install'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/worker.rb:62:in `apply_func'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/worker.rb:57:in `block in process_queue'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/worker.rb:54:in `loop'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/worker.rb:54:in `process_queue'
  /Users/yoonwaiyan/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing isorun (0.1.13), and Bundler cannot continue.

In Gemfile:
  isorun
```

Referenced from https://github.com/eliias/isorun/issues/171 and I followed the steps by pointing the isorun to source from github and installed Rust 1.75.0 in my mac.

**Comment by eliias** [comment]
@yoonwaiyan From the logs I see you are using the `main` branch directly instead of the published gem. Do you have the same issue with the gem?

**Comment by eliias** [comment]
I have fixed the `Cargo.lock`. You can try again.
